### ISSUE TITLE
SPRING sites summary results

### ISSUE THREAD

**Issue by iverkaik** [BiologicalRecordsCentre/SPRING#101] opened 2023-01-05 10:20 UTC
Hi,

I was just checking the SPRING site summary. According to this there is no data for any of these sites, but there have been some data uploading for some of them:

![Screenshot 2023-01-05 at 10 39 02](https://user-images.githubusercontent.com/120505944/210756258-9902fc4a-4182-4690-9e70-636b3d4ce1c3.png)

Can you take a look to this?
thank you!
iraima

**Comment by DavidRoy** [comment] 2023-01-05 10:23
hi Iraima
I think it shows zero as the count is for 'this year', i.e. 2023.
@andrewvanbreda could you change the count column to be all years?  That is more useful for SPRING

**Comment by iverkaik** [comment] 2023-01-05 10:29
mmm I do not see this filtering option in this page though- as you comment- this could be useful for look up for specific results!

thank you!

**Comment by DavidRoy** [comment] 2023-01-05 10:32
The column title suggests it is filtered for the current year only

**Comment by andrewvanbreda** [comment] 2023-01-05 11:32
Hi @iverkaik @DavidRoy 
I will change this as soon as I get a chance.
I can confirm it is definitely for the current calendar year, hence all the zeros, I can see it in the code.

**Comment by iverkaik** [comment] 2023-01-05 11:45
great! good news 🙂
thank you!!
________________________________
De: andrewvanbreda ***@***.***>
Enviado: jueves, 5 de enero de 2023 12:32
Para: BiologicalRecordsCentre/SPRING ***@***.***>
Cc: Iraima Verkaik ***@***.***>; Mention ***@***.***>
Asunto: Re: [BiologicalRecordsCentre/SPRING] SPRING sites summary results (Issue #101)


Hi @iverkaik<https://github.com/iverkaik> @DavidRoy<https://github.com/DavidRoy>
I will change this as soon as I get a chance.
I can confirm it is definitely for the current calendar year, hence all the zeros, I can see it in the code.

**Comment by andrewvanbreda** [comment] 2023-01-05 14:08
Hi @BirenRathod 
Could you pull this report whenever you get a second please. Thanks.

reports/projects/PoMS/eu_pollinator_squares_summary_mappable.xml

**Comment by BirenRathod** [comment] 2023-01-10 13:34
@andrewvanbreda This report has gone live.

**Comment by andrewvanbreda** [comment] 2023-01-10 13:45
@BirenRathod 
Thanks Biren.

@iverkaik @DavidRoy 
This is now live so the totals are no longer just per year.
I can see a couple of further improvements that could be included that I will have to do at lower priority.
It would probably be best to have a year filter, but also to order the report by the count.

For now, if you wish to sort by count, you can click on the Total Count column header (clicking again will reverse the order).

**Comment by iverkaik** [comment] 2023-03-02 09:14
Hi @andrewvanbreda,

I was just checking the summary results and I am only able to see the ones from Spain (transects and pan traps).
![image](https://user-images.githubusercontent.com/120505944/222384188-52b0f022-1588-4c11-8919-4bf6d37aaa67.png)
Could this be changed so that I can see the results from France and Portugal as well? 

thank you,
iraima

**Comment by DavidRoy** [comment] 2023-03-02 09:25
@iverkaik the simplest quick solution is for you to setup a separate user account for each region?  We can then grant national access for each. An interim solution until we can setup a more flexible approach?  Would that be possible for you?

**Comment by iverkaik** [comment] 2023-03-02 09:46
Hello again,

For the transect list, could be possible to add a column to add more information from where the transect is? So can be easier found and also easier to help them.

![image](https://user-images.githubusercontent.com/120505944/222391875-e7463b24-75bd-460b-96fc-a5962390e27e.png)
thank you,
iraima

**Comment by iverkaik** [comment] 2023-03-02 09:49
Hi @DavidRoy,

I think for this stage it is easier (for me for sure) if I can see all the region together, but if not possible, we could set accounts by country. I will talk to coordinators partners in France and Portugal.

thank you,
iraima

**Comment by DavidRoy** [comment] 2023-03-02 09:53
Thanks @iverkaik. We can setup country rules for multiple accounts - e.g. you to review activity plus the France and Portugal partners.

**Comment by andrewvanbreda** [comment] 2023-03-02 10:00
Hi @iverkaik @DavidRoy 

The transects list column issue is because this report is a general data report we use but was not written specifically with SPRING in mind, so the report doesn't understand that the location structure of SPRING is more complex than usual.
David: Let me know if you want me to clone and customise the report, and exactly what extra columns you would want.
I suggest this is removed from this issue and put in a separate one though to avoid confusion.

**Comment by iverkaik** [comment] 2023-03-27 08:29
Hi @andrewvanbreda,
I have some french volunteers that ask if they entered right the data but I cannot access this. Can this be solved?

thank you,
iraima

**Comment by andrewvanbreda** [comment] 2023-03-27 12:50
Hi Iraima,

This page is only available to Administrators and Regional Coordinators by design at the moment.

There are tools for volunteers to view their own data in the "View Results" menu, so they shouldn't need to access that page if they just want to check they have entered the correct data.

Hope that helps

Andy

![Screen Shot 2023-03-27 at 13 48 18](https://user-images.githubusercontent.com/2463614/227944680-944a5db0-1013-4387-b299-b9974f68fdd9.png)

**Comment by iverkaik** [comment] 2023-03-27 13:12
Hi @andrewvanbreda,
Allright, thank you.
iraima

**Comment by DavidRoy** [comment] 2023-05-30 09:58
Closing. Specific follow-on issues to be raised separately

**Closed as completed by DavidRoy** 2023-05-30 09:58 UTC
Labels: Development ready
